<Project Sdk="Snowyyd.NET.Sdk">

  <PropertyGroup>
    <!-- Project -->
    <OutputType>library</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <!-- <RootNamespace>LuaLoader</RootNamespace> -->
    <!-- <AssemblyName>LuaLoader</AssemblyName> -->
    <Configurations>Debug;Release;CPP</Configurations>

    <!-- Lang features -->
    <LangVersion>latest</LangVersion>

    <IncludeLocalUnityReferences>true</IncludeLocalUnityReferences>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='CPP'">
    <DefineConstants>$(DefineConstants);CPP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLua" Version="1.7.9" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='CPP'">
    <PackageReference Include="Il2CppAssemblyUnhollower.BaseLib" Version="0.4.20" />
  </ItemGroup>

</Project>
